version: 2
jobs:
  build:
    docker:
      - image: rust:1.62.0
      - image: postgres:latest
        environment:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
    steps:
      - checkout

      - run:
          name: 'Run tests'
          environment:
            DATABASE_URL: 'postgres://postgres:admin@localhost/testdb?sslmode=disable'
          command: cargo test
